Inner Class: to understand this class more deep.
InnerClass有 3種狀態，依所存在的位置而決定
    (1) Local inner class: by default, inner class is NOT static class.
    (2) Member inner class: This is an API with inner class.
    (3) Anonymous inner class(AIC) == (1) Local inner class

InnerClass有 2種生命類型，依 static 關鍵字
    A. Non-static nested classes are called inner classes.
    B. Nested classes that are declared static are simply called static nested classes.

InnerClass的ERROR類型:
    ERROR: Variable 'X' is accessed from within inner class, need to be declared final.
    ERROR: non-static field 'X' cannot be referenced from a static context.
    ERROR: Inner classes cannot have static declarations.
    ERROR: cannot assign a value to final variable 'X'.